opencast/opencast-editor

- src/main/CuttingActions.tsx
- src/main/MainContent.tsx
- src/main/Timeline.tsx
- src/main/Video.tsx
- src/main/Workflow.tsx
- src/redux/store.ts
- src/redux/videoSlice.ts
- src/redux/videoURLSlice.ts
- src/types.ts
- Examplary Functionality for Delete Button
- Combined video slices
- Examplary segment fetching
> Multiple smaller changes

- .github/workflows/update-test.yml
This fixes the date format used for the deployment location.
> Fix Deployment Date

- src/main/Video.tsx
These patch just removes a few things which aren't actually used or have
no effect at all.
> Video Area Code Cleanup

- src/main/CuttingActions.tsx
This patch adds icons for the “Merge Left” and “Merge Right” segment
actions.
> Icons for Segment Merge Actions

- src/main/CuttingActions.tsx
- src/redux/videoSlice.ts
The active segment can now be combined with neighbouring segments by clicking on the "Merge Right" or "Merge Left" buttons.
> Added functionality to the merge buttons

- src/main/Body.tsx
- src/main/FinishContent.tsx
- src/main/FinishMenu.tsx
- src/main/MainContent.tsx
- src/main/MainMenu.tsx
- src/main/TheEnd.tsx
- src/main/Video.tsx
- src/main/WorkflowConfiguration.tsx
- src/main/WorkflowSelection.tsx
- src/redux/abortSlice.ts
- src/redux/finishSlice.ts
- src/redux/mainMenuSlice.ts
- src/redux/store.ts
- src/redux/videoSlice.ts
- src/redux/workflowPostAndProcessSlice.ts
- src/redux/workflowPostSlice.ts
- src/types.ts
- src/util/client.js
- Adds a finish menu where the user can choose how they wants t end the session
- Additional components for each save, process and abort
- An "end" page where the user gets taken if they should not make changes anymore
- Changes to make "save" and "process" work better with the backend
- Improved typing for redux variables
>  Changed workflow selection to seperate between what the user wants and workflow selection

- src/App.tsx
- src/cssStyles.tsx
- src/main/CuttingActions.tsx
- src/main/FinishContent.tsx
- src/main/FinishMenu.tsx
- src/main/MainMenu.tsx
- src/main/Timeline.tsx
- src/main/Video.tsx
- src/main/WorkflowConfiguration.tsx
- src/main/WorkflowSelection.tsx
Did a bit of cleanup on the css.
- New file for general css styles
- General style for buttons
- Global style
> Summarized css styles

- src/main/FinishMenu.tsx
- src/main/MainMenu.tsx
- src/redux/abortSlice.ts
- src/redux/finishSlice.ts
- src/redux/mainMenuSlice.ts
- src/redux/videoSlice.ts
- src/redux/workflowPostAndProcessSlice.ts
- src/redux/workflowPostSlice.ts
Also removed some duplicate code
> Added typing to redux actions

- src/main/Video.tsx
- src/redux/videoSlice.ts
When active, skips over deleted segments.
- Click the switch left to the play button to change mode
>  Basic functionality for a preview mode.

- src/config.ts
- src/main/Save.tsx
- src/main/Video.tsx
- src/main/WorkflowConfiguration.tsx
- src/redux/videoSlice.ts
- src/redux/workflowPostAndProcessSlice.ts
- src/redux/workflowPostSlice.ts
- src/types.ts
- (was already the new API for the Save and Save&Process POST requests)
- Adds Tracks to POST requests as required
- Created config for global variables
> Changes webrequests from the old API to the new API

- src/main/Video.tsx
This patch updates the title which gets a little bit more space while
using the available white-space more effective. This also protects
against overly long title which are ended in a horizontal ellipsis,
ensuring that they never get more than a single line.
---
Preview:
> Title Style

- src/main/MainMenu.tsx
> Stopped video playback on menu switch

- src/cssStyles.tsx
- src/main/CuttingActions.tsx
- src/main/Discard.tsx
- src/main/Finish.tsx
- src/main/FinishMenu.tsx
- src/main/MainContent.tsx
- src/main/MainMenu.tsx
- src/main/Save.tsx
- src/main/Timeline.tsx
- src/main/Video.tsx
- src/main/WorkflowConfiguration.tsx
- src/main/WorkflowSelection.tsx
Adds basic keyboard navigation (Tab, Shift+Tab, Enter, Space). Also adds some aria labels and semantic tags. Related to #70
Does not reach the goal of making the app fully keyboard navigable. The timeline and the scrubber in particular require more consideration.
> Basic aria labelling and keyboard navigation

- src/main/Timeline.tsx
Loses the red color for better contrast and adds triangles to help with visual clarity
> Changed scrubber appearance

- src/main/Timeline.tsx
- src/util/utilityFunctions.ts
- Can now tab onto the scrubber and move it left/right
- Can now tab onto the segments on the timeline
- Added ARIA labels for information
Intended to help with both #84 and #85.
> Make the timeline navigable by keyboard

- src/main/Timeline.tsx
The spinner that should show during waveform generation now actually shows!
> Fixed spinner for waveform generation

- src/cssStyles.tsx
- src/main/CuttingActions.tsx
- src/main/Save.tsx
- src/main/TheEnd.tsx
- src/main/Video.tsx
- src/main/WorkflowConfiguration.tsx
- src/main/WorkflowSelection.tsx
This PR adds additional information to assist users with learning how to use the website and the general status of the website.
> Added various tooltips and aria labels

- src/main/Video.tsx
Now at least tells the user that something went wrong instead of just showing a black box.
> Added error display for video elements

- public/editor-settings.toml
- src/main/WorkflowConfiguration.tsx
- src/main/WorkflowSelection.tsx
- src/redux/videoSlice.ts
- src/redux/workflowPostAndProcessSlice.ts
- src/types.ts
Also handled two minor edge cases
> Added workflow descriptions

- src/cssStyles.tsx
- src/main/Save.tsx
- src/main/Video.tsx
- src/main/WorkflowConfiguration.tsx
Also done some code refactoring in that regard.
> Added some error messaging to the initial get request.

- src/main/CuttingActions.tsx
- src/main/WorkflowConfiguration.tsx
- src/main/WorkflowSelection.tsx
- src/types.ts
Also fixed an issue with starting workflows
> Removed functionless UI for deployment

- src/main/Discard.tsx
- src/main/Save.tsx
- src/main/TheEnd.tsx
- src/main/WorkflowSelection.tsx
Updates some of the text to be slightly more professional.
> Various text updates

- src/main/Video.tsx
The duration is now displayed alongside the current time.
Also did some code cleanup, resulting in the play button now being truly centered.
Solves #115.
> Added duration display

- src/main/Video.tsx
- src/redux/videoSlice.ts
Removed todos that are now better represented as github issues
> Remove Todos

- LICENSE
This patch adds the Apache 2 license to the project.
> Add Apache 2 License

- src/main/Video.tsx
> Proper title for time display elements

- src/main/Video.tsx
Now the toggle can also be toggled by clicking the describing text next to it.
Solves #124
> Made text "Preview Mode" clickable

- src/main/CuttingActions.tsx
> Update title text for cutting actions

- src/main/WorkflowSelection.tsx
This patch slightly improves the workflow selection view:
- We shouldn't recommend workflows which might not exist due to an
administrators chiuce and should hope that admins properly lable them
instead.
- This adds some padding to make this look better an smaller screens
- We shouldn't show a development(?) comment when there is no workflow
description.
> Workflow Selection View Improvements

- .github/workflows/check-merge-conflict.yml
This patch adds a simple GitHub Actions workflow which will
automatically check for merge conflicts.
> Automatically Check for Merge Conflicts

- src/main/Save.tsx
- src/main/WorkflowSelection.tsx
- Now displays a more proper version of the page when there are no workflows available
- Added a new version of the page for when there is exactly one workflow available
Somewhat resolves #128
> Updated the workflow selection rendering process

- src/main/WorkflowSelection.tsx
Effectively does the same thing as #175, but I broke #175 and making a new PR is faster than fixing the thing.
> Changes Processing Label

- public/editor-settings.toml
The current default event is broken. Therefore I'm changing it to another event, so interested tester can see something less broken.
> Changed default event for the test servers

- README.md
Also added a section on how to make a new release of the frontend for Opencast. Resolves #276
> Updated readme with current information

- src/i18n/locales/en.json
- src/main/Metadata.tsx
- src/main/Save.tsx
- src/main/WorkflowConfiguration.tsx
- src/main/WorkflowSelection.tsx
Resolves #298, also fixes a spelling mistake
> Fixed spelling and i18n error links

- README.md
This PR adds a notice about the Crowdin project I set up for this repository. If you are familiar with Crowdin, please check if everything is set up as you would expect it to be.
Resolves #274.
> Adds a notice for Crowdin for translations

- package-lock.json
- package.json
- src/main/MainContent.tsx
- src/main/Save.tsx
- src/main/WorkflowConfiguration.tsx
- src/redux/metadataSlice.ts
- src/redux/videoSlice.ts
Will ask the browser to show a prompt to the user when leaving the editor with unsaved changes (either in the cutting view or in the metadata).
Resolves #97
> Added warning when leaving with unsaved changes

- src/main/Timeline.tsx
This removes yet another unhelpful title.
> Remove unhelpful title

- src/main/MainContent.tsx
This patch simplifies the selection of which view to display, not
relying on manual state specifications for the defaults.
> Simplify View Selection

- public/editor-settings.toml
- src/config.ts
This patch adds a little bit more structure and more documentation to
the configuration file, explaining usage, types and defaults.
> Configuration Documentation

- public/editor-settings.toml
- src/config.ts
- src/cssStyles.tsx
- src/i18n/locales/en.json
- src/main/MainContent.tsx
- src/main/MainMenu.tsx
- src/main/TrackSelection.tsx
- src/redux/videoSlice.ts
- src/types.ts
This patch adds the ability to select or deselect tracks to allow for the removal of unwanted material.
This is a variant of pull request #398 with a much simplified user interface.
This closes #398
> Simple Track Selection

- package.json
> Removed web-vitals from package.json

- playwright.config.ts
Added timeout of 60 seconds to playwright.config to reduce timeout-errors while testrun.
> Added Timeout

- src/globalKeys.ts
- src/i18n/config.tsx
- src/i18n/locales/en-US.json
- src/main/CuttingActions.tsx
- src/main/KeyboardControls.tsx
- src/main/TrackSelection.tsx
- src/main/Video.tsx
- src/main/WorkflowSelection.tsx
This should fixes #644
Translation now works, but the missingKey-error is still there, even though the key is translated.
> Fixed missing translations

- package-lock.json
- package.json
- src/redux/videoSlice.ts
> Update Typescript to 4.7.4

- .github/workflows/cleanup-deployments.yml
Removes deployments after a PR was merged or closed.
> add cleanup workflow

- src/main/Video.tsx
Currently, if video playback has reached the end of the video, pressing the play button again does nothing. With this commit, pressing the play button instead starts the video from the beginning.
Resolves #833
> Start playback from beginning if at the end

- src/redux/__tests__/videoSlice.test.ts
This patch updates tests that were failing.
> Updated tests that were failing

- .github/workflows/create-release.yml
- .github/workflows/playwright-test.yml
- .github/workflows/update-test.yml
- .github/workflows/update.yml
This patch updates the Node.js versions used for testing and building the release version to the current LTS version.
> Update to Node 18

- src/main/WorkflowSelection.tsx
- src/redux/videoSlice.ts
correct workflow ordering  including when displayOrder undefined.
replaces PR#1101
> fix #997, correct workflow ordering 

- .eslintrc.js
- src/config.ts
- src/main/Cutting.tsx
- src/main/CuttingActions.tsx
- src/main/Finish.tsx
- src/main/Lock.tsx
- src/main/Metadata.tsx
- src/main/Save.tsx
- src/main/SubtitleEditor.tsx
- src/main/SubtitleListEditor.tsx
- src/main/SubtitleSelect.tsx
- src/main/SubtitleTimeline.tsx
- src/main/Thumbnail.tsx
- src/main/Timeline.tsx
- src/main/TrackSelection.tsx
- src/main/VideoControls.tsx
- src/main/VideoPlayers.tsx
- src/main/WorkflowConfiguration.tsx
- src/main/WorkflowSelection.tsx
- src/redux/errorSlice.ts
- src/redux/finishSlice.ts
- src/redux/mainMenuSlice.ts
- src/redux/subtitleSlice.ts
- src/redux/videoSlice.ts
- src/redux/workflowPostAndProcessSlice.ts
- src/redux/workflowPostSlice.ts
- src/themes.ts
- src/types.ts
This commit activates the default eslint line lenght of 120 and fixes the resulting warnings.
> Activate eslint line length

- src/i18n/config.tsx
- src/main/SubtitleListEditor.tsx
- src/main/SubtitleSelect.tsx
- src/main/SubtitleTimeline.tsx
- src/main/Thumbnail.tsx
- src/main/Timeline.tsx
- src/main/TrackSelection.tsx
- src/main/VideoPlayers.tsx
- src/redux/subtitleSlice.ts
This replaces some `any` types with more specific ones. No functional changes.
> Specify more types

- .eslintrc.js
- src/main/Header.tsx
- src/main/Tooltip.tsx
- src/main/VideoPlayers.tsx
> Enforce eslint no-non-null-assertion

- .eslintrc.js
- src/main/Timeline.tsx
Removes some eslint exceptions for rules we are
already (almost) following anyway.
> Remove already enforced eslint exceptions

- src/main/KeyboardControls.tsx
Fixes a web console error message about unique keys in the Keyboardcontrols. Afaik this did not cause any bugs, but we should still do it "right" nonetheless.
> Fix unique key error in keyboard controls

- src/i18n/locales/de-DE.json
- src/i18n/locales/en-US.json
- src/main/Timeline.tsx
- src/redux/videoSlice.ts
- src/themes.ts
Cut marks can be moved via drag and drop. 
Related to #1132
> Movable cut marks

- .github/dependabot.yml
This patch adds a Dependabot configuration for GitHub Actions.
> Dependabot configuration for GitHub Actions

- src/main/TrackSelection.tsx
- src/redux/videoSlice.ts
Typing issues my IDE reported me that for some reason were not fixes. This fixes them.
> Fix random typing issues
