.github/workflows/update.yml
This patch automates a deployment of the `main` branch to the `gh-pages`
branch which will then be available at https://editor.opencast.org
This fixes #7
=> Automate Deployment

.github/workflows/update-test.yml
This patch adds a workflow which will automatically create a test build
of Opencast Editor and deploy it to test.editor.opencast.org.
The exact location of the deployment is then announced at the pull
request as comment.
---
An example pull request can be found at
https://github.com/lkiesow/opencast-editor/pull/1#issuecomment-733880738
=> Automate Test Deployment

src/main/Video.tsx
This patch reduces the video control size while slightly increasing the
space between controls. The buttons should still be big enough and
important functionality like playback couls (and should) get additional
controls as well (space bar, clicking the videos).
---
EDIT: Also fixed the jumping play button when the video is playing.
=> Video Control Style

src/main/CuttingActions.tsx
This patch changes the style of the cutting tools so that they are
displayed as one line with the icon left of the text. This saves a lot
of vertical space and should still be easy tu use.
=> Slim Cutting Tools

src/main/Timeline.tsx
This patch reduces the border radius and turns the border a consistent
white color.
Reasoning:
- the border radius looked a bit odd with the scrubber extending over the edge
- the different colored borders looked somewhat odd when you had deleted
and non-deleted segments right next to each other
- the white border causes a clean separation of segments
This supersedes #20
=> Timeline Border

src/main/MainContent.tsx
This PR fixes issue #44 by removing "width=100%".  As flex items grow to fill the container anyway, explicitly setting the width is no longer necessary.
=> Fixed horizontal overflow (Shows scrollbar)

src/main/Timeline.tsx
Fixes issue #41 by setting the scrubber position through a useEffect hook. Unsure whether this is the proper way to do this as it requires to surpress a warning.
=> Fixed scrubber position not changing with timelinewidth

public/index.html
This patch updates the title to not show „React App“ in the browser bar.
=> Page Title

src/config.ts
You can now pass an id in the form of `?mediaPackageId=838b9eb3-d44e-47a1-b69e-b10e65b4ec92` to the editor to load the mediapackage you want.
=> Allows passing a mediaPackageId for testing

src/main/Timeline.tsx
Currently segments are nearly impossible to distinguish if you can't rely on your color-vision. This PR adds further visual cues to help distinguish between deleted and not-deleted segments, as well as the currently selected segment and every other segment. Related to #70
=> Colorblind optimization for segment display

src/main/Video.tsx
This change is intended to better inform the user what the preview mode switch is about. As there is no icon distinctly representing such a feature, text is preferred.
=> Replaced icon for preview mode with text

src/main/Video.tsx
PiP grants users single video controls, which we do not want (everything should be controlled centrally).
Therefore, this PR disables PiP.
Except in Firefox, because Firefox doesn't want PiP to be disabled.
=> Disables Picture-in-Picture Mode for video players

src/main/Video.tsx
React players have `tabIndex=0` per default. Setting it to `-1` avoids focusing on the video players when using keyboard controls (which you should not be able to do, since you interact with the videos only through player-external controls).
=> Added negative tabIndex for video players

src/main/MainContent.tsx
It's good to have title for elements you can interact with to provide
additional explanations but these are not helpful to users and provide
no more information except telling developers what element they are
hovering over.
=> Remove Unhelpful Titles

src/main/Discard.tsx, src/main/Save.tsx
This patch shortens the texts for saving and discarding the current
project and add a header alike the one you get when choosing to start
processing.
=> Shorten and align save and discard

.vscode/launch.json, package-lock.json, package.json, src/App.test.tsx, src/redux/__tests__/videoSlice.test.ts, src/redux/videoSlice.ts
Instead of spouting error messages, `npm test` should now actually run tests. To commemorate this, this PR includes some unit tests for the reducers of `videoSlice`.
=> First basic unit test for reducers of videoSlice

src/redux/videoSlice.ts
The problem was that it was attempted to call another reducer, but with wrong arguments. Now the code shared by both reducers have been put into another function.
Closes #164
=> Fix "`currentlyAt` not updating" bug introduced in 7b501e0

src/main/FinishMenu.tsx
Allows flexWrap in the finish menu ("Save, Process, Discard") to avoid squishing the large buttons on smaller resolutions.
This is the easiest solution to #129, but may not look as good, since the buttons do not immediately change from row to column. Another solution would be media-queries, but those are require specifying a width and are thus not quite as dynamic.
=> Introduced wrapping to the finish menu

.github/workflows/update.yml
The build and deployment currently fails if a commit causes no actual
changes to end up in the final build of the editor. This patch fixes the
problem by executing `git commit` only if there are actual changes.
This fixes #25
=> Fix Build with no changes

public/index.html
Removed a 'link' tag for apple-touch-icons, which we neither have nor could make any use of. Resolves #207
=> Removed apple-touch-icon from index.html

src/main/Body.tsx, src/main/MainContent.tsx, src/main/Video.tsx
The editor currently contains a lot of non-helpful and often confusing
title tags at what appears to be random HTML elements. This is not
helpful.
This patch removes some, but not all of these.
This is related to #262
=> Remove Confusing Title Tags

src/i18n/locales/en.json
The text describing which workflow will be started unnecessarily escapes
quotation marks twice.
=> Incorrectly Escaped Start Workflow Text

src/main/Metadata.tsx
This patch actually assigns the existing labels for metadata fields to
the form inputs so that they are related. This is important for
usability (users can now click the label) and accessibility (inputs now
get a proper description).
=> Assign Labels to Form Fields

src/main/Timeline.tsx, src/util/waveform.js
Exceptions in the waveform workers were not caught. This resulted in the permanent display of the message generating waveform. Now if the waveform generation fails for whatever reason, the user is informed. A more detailed error message is logged to the console.
Resolves #157
=> First example of actual error handling for exception in the waveform workers

src/main/Timeline.tsx
The scrubber now sends live updates to the other components when it is moving.
This seems to have a high performance impact, due to repeated calls to seek() in the video players. Haven't yet found a good solution to that problem.
Resolves #74
=> Update time when moving scrubber, instead of only at start and end

src/globalKeys.ts, src/main/Timeline.tsx
Allows the scrubber to be moved by the arrow keys in addition to the already defined hotkeys. 
This PR still keeps the already defined hotkeys (Ctrl+Alt+J etc.) as the default hotkeys, since the arrow key behaviour is overriden by the orca screenreader when using it. Preferably this PR is tested with other screenreaders as well.
Contains #305, so that one should be merged first.
Resolves #300.
=> Rework scrubber hotkeys arrows

src/i18n/locales/en.json, src/main/Body.tsx, src/main/Error.tsx, src/main/Video.tsx, src/redux/errorSlice.ts, src/redux/store.ts, src/util/client.js
Introduces an error page that can be displayed in case of an unrecoverable error.
Failures that occur when fetching information for Opencast will now cause the error page to appear.
Can be tested by calling the editor with a non-existant mediaPackageId, for example `?mediaPackageId=nonsense`.
Partially resolves #162 (Error page is not yet shown if the media package exists but the contents are faulty).
=> Added error page

src/main/TheEnd.tsx
After clicking on "start processing" or "discard changes", the final page that is shown has scroll bars for no reason. These are now removed.
=> Removed scroll bars from TheEnd

src/main/Timeline.tsx
The scrubber would sometimes move vertically when dragging. This enforces setting y to 0.
Mentioned in #313.
=> Stopped vertical movement of scrubber

src/main/Timeline.tsx
Moves the scrubber head to the top of the timeline, to make the waveform more visible.
Also changes the design to be more in line with traditional video editors.
Resolves  #153
=> Change scrubber handle design

src/i18n/locales/en.json, src/main/Body.tsx, src/main/Landing.tsx
The editor relies on a mediapackage ID to function properly. Instead of showing an error when it is missing, this instead displays a landing page with various information.
To test this, remove the field `mediaPackageId` from `public/editor-settings.toml` and call the editor without the parameter `
?mediaPackageId=[id]`.
Resolves #163.
=> Added landing page

package-lock.json, package.json, src/i18n/locales/en.json, src/main/Metadata.tsx
For whatever reason, `mui-rff` disables the automatic datetime validation from material-ui, so we have to do the validation ourselves.
Resolves #297
=> Added a validator for datetime metadata fields

src/main/Timeline.tsx, src/util/waveform.js
The error callback for the waveform generation was not working as a proper callback, but would always throw an error. By coincidence, this was hardly noticable on shorter videos, but very noticable on longer ones.
This fixes the callback. "Generating waveform" should now be displayed up until the waveform shows up, even on longer videos. In case of an error (e.g. when the video has no audio), "Waveform could not be generated" will still show.
=> Fixed waveform generation always throwing error

src/redux/videoSlice.ts
When skipping deleted segments during preview mode playback, the skip ended up at the end of the deleted segment, not the start of the next non-deleted segment, causing weird visual flickering for a brief moment. This fixes that.
Partially resolves #198. I would prefer discussing the issue of whether the cutting action buttons should be disabled during (preview) separately from this.
=> Fixed preview mode playback not jumping to next non-deleted segment

public/editor-settings.toml, src/config.ts, src/main/Metadata.tsx
Added an option to the editor-settings that lets users control which metadata catalogs and fields are displayed in the editor.
Resolves #38. Does not resolve the follow up request regarding read-only configuration in the same issue.
=> Added a config option for displaying metadata fields

src/main/MainMenu.tsx
Instead of selecting the translation key for every menu item manually,
this patch selects them automatically based on their state name.
=> Automate Translation Key Selection

public/editor-settings.toml, src/config.ts, src/main/Metadata.tsx, src/redux/metadataSlice.ts
Each field in a metadata catalog can now be set to be editable by the user or not.
Furthermore, this reworks how settings are written in the editor-settings.toml to allow specifiying multiple attributes for one metadata field. If an attribute is not specified, a default is assumed instead.
To test this, play around with example definitions in the editor-settings.toml and observe how they change the metadata ui.
=> Added readonly as metadata config option

README.md, build-release.sh
This patch simplifies the release script by removing the necessity for
manually editing the resulting tarball.
=> Simplify Release Scripts

public/editor-settings.toml
This patch switches from the edifor development server to Opencast's
official test server to allow for shutting down the other machine.
=> Switch to Opencast Test Server

src/main/Landing.tsx
This patch adds a direct link to the video editor documentation in
Opencast instead of just linking the main docs page.
=> Link Documentation Directly

src/config.ts
This patch prevents users from crafting URLs which would make the editor
reach out to a non-configured Opencast, potentially misleading users:
https://opencast.uni-osnabrueck.de/editor-ui/index.html?mediaPackageId=b8d2e0a3-d447-4cd1-94e5-facbc2249f22&someOther=LongAndConfusingParameter&opencast.url=https://malicious.opencast.org
…will not work any longer.
=> Disallow Overwriting Opencast Parameters

src/redux/videoSlice.ts
This makes the comparison between two display order entries a little bit
simpler.
=> Simplify display order compare

src/main/Save.tsx, src/main/WorkflowConfiguration.tsx
The multiple post requests that are send when saving or starting processing are now sent sequentially. Requests wait for their previous requests to return with a successful response code.
This change is supposed to help avoid race conditions than seemingly occur when sending post requests to the metadata and editor endpoints in Opencast at the same time.  Therefore this hopefully resolves #353 resolves #354 resolves #363. It might be worth to look at why exactly these errors occur in the backend.
=> Send POST request sequentially

.github/workflows/update-test.yml
This patch adds Nadine to the list of authors for which the automated
test deployments are allowed to run.
=> Allow Tests Deployments from Nadine

.github/workflows/deploy-crowdin-keys.yml, .github/workflows/update-test.yml, .github/workflows/update.yml
If multiple GitHub Actions workflows try to simultaneously deploy to the
same environment, some of them fail with conflicts. This patch that only
a single workflow accessing the same resource runs at a time.
The test deployment will wait for the other workflows to finish. The
demo deployment to editor.opencast.org and to Crowdin will cancel old
workflows since their data will be overwritten by the new workflow
anyway.
=> GitHub Actions Concurrency

src/index.css
This fixes #465
Added textarea and input to index.css. Now the font and the size is the same. (It only affects metadata page)
=> Changed font on metadata editor

src/main/Metadata.tsx
This fixes #464
Centered formular, also added minWidth because the formular looked too small on full-width.
=> Centered Metadata-Page

src/main/Metadata.tsx
This may fixes #293
Commented on this Issue:
To point 1: It seems not possible, that the Modal switches to Time-Tab after selecting a Date (Couldn't find anything about that)
To point 2: It is possible, that the Modal doesn't close after selecting a Time, so you don't have to reopen and reselect the Modal, when you accidentally selected the false Time (minutes)
=> Calendar and Time Input

.github/workflows/update-test.yml
Adding concurrency groups for the test deployment caused some of the
pending jobs to be canceled as GitHub Actions only allows a single
pending workflow in a concurrency group:
> When a concurrent job or workflow is queued, if another job or
> workflow using the same concurrency group in the repository is in
> progress, the queued job or workflow will be pending. Any previously
> pending job or workflow in the concurrency group will be canceled. To
> also cancel any currently running job or workflow in the same
> concurrency group, specify cancel-in-progress: true.
This patch switches to the [Turnstyle](https://github.com/softprops/turnstyle) action instead, which will make
the job wait for previous workflows. This should have the intended effect.
=> Fix Test Deployment

package-lock.json, package.json
This patch removes the unused `date-fns` library. We already use
`@date-io/date-fns` instead. There is no need to track and update
`date-fns` directly.
=> Remove unused library `date-fns`

.github/workflows/playwright-test.yml
This patch fixes the configuration for using the mock data in the
PlayWright tests on GitHub Actions.
=> Actually Mock Data for Playwright Tests

.github/workflows/update-translations.yml, src/i18n/locales/de.json, src/i18n/locales/es.json, src/i18n/locales/fr.json, src/i18n/locales/ja.json, src/i18n/locales/nl.json, src/i18n/locales/pt.json
This patch adds a workflow to automatically update the translations on a
weekly basis by downloading the current state from Crowding and
committing them to the repository.
This fixes #406
=> Automatically Update Translations

tests/navigation.test.ts
Currently the Playwright tests for the navigation bar expect four specific menu items to be present. However, every menu item besides "Cutting" and "Finish" is configurable to be present or not. Therefore I'd like to propose to only check for the actually required menu items, instead of some arbitrarily defined set.
=> Relax Playwright tests for the navigation bar

README.md
This patch adds documentation for several configuration options to the
main readme file.
Do not merge before #642.
=> Document Configuration Options

README.md, public/index.html, public/manifest.json
Calling this editor the "Standalone Editor" has long been abandoned. This PR removes the last remaining references to that.
Resolves #299
=> Get rid of stand-alone naming leftovers

src/main/Timeline.tsx, src/redux/videoSlice.ts
This PR will display pre-generated waveform images sent from the Opencast backend. If none are sent, waveform generation will still kick in like normal.
This requires Opencast workflows to include the "Waveform" operation and add the generated file to the internal publication.
Waveform generation seems to crash the editor for very long video/audio files, so this PR provides a workaround that does not require disabling waveform generation outright.
Also requires https://github.com/opencast/opencast/pull/3780 to be merged.
Probably resolves #501
=> Display waveform images from the backend instead of generating them

src/main/WorkflowSelection.tsx
Fixes a problem where the workflow id was not sent to Opencast when saving & processing when only a single workflow is available for processing.
=> Ensure that the workflow id is set for single workflow

src/main/FinishMenu.tsx
This fixes #649
Added some padding left and right.
=> Padding for long button labels

src/main/WorkflowConfiguration.tsx, src/main/WorkflowSelection.tsx
Some dispatch hooks were placed uncondoditionally, resulting in them being called on every rerender. While that is in and of itself not an issue (redux will easily notice that the repeated dispatches would not change anything and ignores them), it can trigger redux' infinite-loop-prevention hook, causing the website to crash.
=> Avoid calling dispatch on every rerender

src/redux/videoSlice.ts
Resolves #740
If the last segment is deleted and preview mode is enabled, the video player now behaves more like you would expect from a video player
=> Specify preview mode behaviour for last segment

src/main/MainContent.tsx, src/main/Save.tsx, src/redux/metadataSlice.ts, src/redux/videoSlice.ts
The component that is responsible for setting "has unsaved changes" to false was destroyed before getting a change to set that. Now it's not anymore.
Also renames two selectos to fit the naming convention.
Resolves #742
=> Dont show unsaved data popup after saving

src/main/TrackSelection.tsx
The CSS property `border-bottom` for the menu headings on the Track Selection was hard coded to `1px solid white`, which works great for the dark theme, but not so much for the light theme.
Before:
After:
=> make TrackSelection respect theme selection for menu headings

.github/workflows/check-label.yml
The section "How to cut a release for Opencast" in the README.md states in the first section:
> Make sure all merged pull requests have proper type: labels. They are
> used for generating the release notes.
With this new github action this step gets automated.
=> Add workflow to check proper lable usage

src/cssStyles.tsx
The presenter and contributor fields in the metadata tab use a combined select input control with multi-select enabled. The actual <input> is only a few pixels wide, so when hovering over the control, it's not showing a text cursor indicating the possibility to input new text.
This commit sets the cursor on the `valueContainer` component to `text` and resets it to `default` on the `multiValue` component.
For the list of available components for React-Select see: https://react-select.com/components
Fixes: #785
=> change cursor style to text for react-select multi CreatableSelect

.github/workflows/update-translations.yml
This allows updating the translations manually just before cutting a release.
=> Enable running the 'Update translations' workflow manually

public/editor-settings.toml, src/config.ts, src/cssStyles.tsx, src/i18n/locales/en-US.json, src/main/MainContent.tsx, src/main/MainMenu.tsx, src/main/Thumbnail.tsx, src/main/Timeline.tsx, src/main/Video.tsx, src/redux/videoSlice.ts, src/types.ts
Adds a new view which allows users to create thumbnails for their events.
Allows users to:
- Generate a thumbnail from a video at a selected point in time.
- Upload a thumbnail.
- Set the same thumbnail for all videos.
- Discard any changes they made.
Has a "simple" and a "professional" mode.
- Simple: For when you only care about one primary thumbnail.
- Professional: When you want to be able to change all the thumbnails in the subflavor.
Requires Opencast backend PR to function: https://github.com/opencast/opencast/pull/4086
=> Thumbnail Editor

README.md
As the check-proper-label-usage works as designed, the corresponding line in the README.md can now be removed. See #795
This commit also makes the creating and pushing of a new tag more copy&paste-able and less error-prone. It mentions the 'update translations' workflow to (optionally) run it manually.
=> update readme section 'How to cat a release for Opencast'

src/main/Landing.tsx
If you blindly copy and paste the query parameter into your browsers address window (and change the mp id), you just land on the landing page again, leaving you a bit stumped before figuring out the typo.
=> Remove superfluos "=" on landing page

.github/workflows/cleanup-deployments.yml, .github/workflows/create-release.yml, .github/workflows/deploy-crowdin-keys.yml, .github/workflows/playwright-test.yml, .github/workflows/update-test.yml, .github/workflows/update-translations.yml, .github/workflows/update.yml
This improves and fixes several GHA workflows.
Add a `editor-settings.toml` just for deployments to editor.opencast.org and test.editor.opencast.org. This enables setting certain config values for testing deployments we do not want to ship (yet).
- Update to actions/checkout@v3 and actions/setup-node@v3
- Run GitHub Actions on the latest ubuntu
The steps were running in different working directories. Now they all run relative to GITHUB_WORKSPACE
Currently, the Test & Deploy workflow only runs for selected pull requests. Adding a bunch of people to the list and keeping it up-to-date could turn out to be cumbersome. So this adds an additional workflow job and uses `TheModdingInquisition/actions-team-membership@v1.0` to check the membership of the person opening the PR. If the person is part …
=> Improve GHA

editor-settings.toml, public/editor-settings.toml
This patch splits the configuration file to provide two separate versions:
- `editor-settings.toml` which is our recommended configuration for production, has all the default settings and documenta all configuration options.
- `public/editor-settings.toml` which is used for development (`npm run start` will use this) and for demo deployments. It should enable new features by default to make testing easier.
This closes #837
=> Split demo and production configuration

.github/workflows/update-test.yml
Secret names must not start with `GITHUB_ `.
=> fix Test & Deploy workflow

.github/workflows/update-test.yml
This patch does not only check the developers, but also the committers
teams and runs the test and deployment steps if the pull request author
is in one of the teams.
=> Test and deploy all organization member pull requests

src/cssStyles.tsx
The presenter and contributor fields in the metadata tab use a combined select input control with multi-select enabled. When typing the text is hardly visible in the dark theme, as it's grey on a dark background.
This commit sets the colour on the `input` component to `theme.text` to respect the theme selection.
For the list of available components for React-Select see: https://react-select.com/components
Fixes: #813
=> change text color for react-select multi CreatableSelect

.github/workflows/update-test.yml
This patch fixes the test and deploy GitHub Actions workflow if the pull request author is Dependabot by skipping the team membership test if the pull request source is already the target repository.
This fixes #877
=> Fix Dependabot test deployment

src/main/SubtitleSelect.tsx, src/main/SubtitleTimeline.tsx, src/main/SubtitleVideoArea.tsx
Forces the marker to the front via CSS.
Resolves https://github.com/opencast/opencast-editor/issues/858
(Contains https://github.com/opencast/opencast-editor/pull/892)
=> Fix timeline marker in subtitle-editor being obscured

src/main/SubtitleSelect.tsx, src/main/SubtitleVideoArea.tsx, src/main/Video.tsx
Hotkey for the preview button was hardcoded and would thus show incorrectly for i.e. MacOS users.
(Contains https://github.com/opencast/opencast-editor/pull/892)
=> Fix preview button tooltip hotkey hardcoded

src/main/MainContent.tsx, src/main/SubtitleSelect.tsx, src/main/SubtitleVideoArea.tsx
At some point the flexDirection for the gear menu got commented out,
causing it to look somewhat strange. This changes the flexDirection back
to column.
Resolves #850.
(Contains #892)
=> Gear menu flow

src/main/SubtitleSelect.tsx, src/main/SubtitleVideoArea.tsx
Recent dependency updates have caused a type mismatch. This quells the mismatch by basically replacing null with undefined.
=> Fix type mismatch for Select labels

.gitignore
This patch adds a few editor specific files to the `.gitignore` to to prevent them from accidentally being committed.
=> Add editor files to gitignore

src/main/Subtitle.tsx
This patch just simplifies the return statement of the subtitle container's render function.
=> Simplify code

src/i18n/locales/en-US.json, src/main/SubtitleSelect.tsx
This patch shows all existing subtitles that are recognized by Opencast and sent to the editor in the user interface instead of just showing subtitles which exactly match a specified language flavor.
Which subtitle tracks are sent from Opencast to the front-end is still configurable in the editor service.
This also does not allow users to create arbitrary subtitle tracks. They have to already exist.
This fixes #826
=> Show all existing subtitles

src/main/Thumbnail.tsx
This patch limits the thumbnail generator to only show a selection for video tracks, omitting things like audio or subtitle tracks.
The downside of this is obviously that pure audio streams aren't supported. But they aren't really supported in the current user interface anyway.
This fixes #853
=> Thumbnail for video streams only

editor-settings.toml, public/editor-settings.toml, src/config.ts, src/main/SubtitleSelect.tsx
This patch allows users to specify icons for languages selectors displayed in the subtitle editor. Users have to specify the selectable languages anyway and the algorithm used before guessed wrong for popular languages like English.
If no icon is specified for a language, the selector will simply omit the icon and display just the label.
This fixes #825
=> Icon Configuration for Languages

src/i18n/locales/en-US.json, src/main/ThemeSwitcher.tsx
The appearance selector, which is used to select themes for accessibility is missing an aria-label.
=> Add aria-label to theme selector

src/i18n/locales/en-US.json
This PR replaces all occurrences of the term scrubber with the term timeline marker. The goal is to use a self-explanatory term.
Other possibilities:
- timeline marker
- current time marker
- playhead
The PR is based on https://github.com/opencast/opencast-editor/pull/840
=> Replace scrubber language strings

.github/workflows/playwright-test.yml, playwright.config.ts
This patch makes Playwright take screenshots of failing tests and will upload them alongside the test result report to the GitHub Actions workflow artifacts. This makes it easier to get information about what is failing if a test is failing.
This also limits the number of retries: If we have to retry three times to pass a test something is definitely wrong. Either with the code or with the test.
=> Keep Playwright Test Results

src/main/Thumbnail.tsx, src/main/Timeline.tsx
In the thumbnail editor, a timeline similar to the one in the cutting view is visible. One thing they share is highlighting individual segments on the timeline. This makes no sense in the thumbnail editor, as you cannot interact with the segments at all. This fixes that.
Resolves #834
=> Do not highlight timeline segments in thumbnail editor

.github/workflows/playwright-test.yml
This patch fixes the problem that the initial runs of Playwright fail on pull requests all the time. While they eventually succeed on the second run, the failing tests still leave lots of unnecessary warnings on GitHub Actions.
The problem seems to be that the React test server can sometimes be awfully slow when starting up, causing the initial runs to fail with an empty page.
To prevent this, this pull request actually build the Editor instead before running the tests on the pre-build project.
This fixes #846
=> Fix Failing Playwright Tests

src/cssStyles.tsx, src/main/MainMenu.tsx, src/redux/themeSlice.ts, src/themes.ts
Shows a slightly grey (whitesmoke) background and white input fields in light mode.
This changes should make the input fields better visible, since they are currently displayed in the same background color.
Resolves #932
=> Improve visibility of input fields

editor-settings.toml, public/editor-settings.toml
We should use local names as language, as it is for "Deutsch" and "English" already. So it must "Español" instead of "Spanish".
=> Fix language wording ES to local name

src/main/SubtitleVideoArea.tsx
The implementation simply omits the subtypes if subtypes of all tracks are equal
Resolves #927
=> Omit "preview" in video flavors drop down of subtitle editor

src/i18n/config.tsx
Currently, some language resources will be loaded after the rendering which leads to missing translation key errors. This commit changes the asynchronous loading of the resource files to synchronous loading.
This is not the most elegant solution, as it delays the rendering. In the best case, the files should still be loaded asynchronously and be integrated in the `initialize` promise of `index.tsx`, for example.
Fixes #766
=> Fix language resources loading

src/main/SubtitleListEditor.tsx, src/main/SubtitleTimeline.tsx, src/redux/subtitleSlice.ts, src/types.ts, src/util/utilityFunctions.ts
The subtitle editor requires unique identifiers to work properly. However, the webvtt parser does not provide such ids. WebVTT cue ids are not a good fit either, as they hardly qualifiy as identifiers.
This adds a new field to the subtitle cues to act as a unique identifier. This should also stop the editor from adding randomly generated WebVTT cue ids to subtitle files.
Helps with #941.
=> Add internal identifier for subtitle cues

.github/workflows/check-icla.yml
This patch adds the ICLA check used in Opencast's main repository. The editor follows the same rules and regulations and contributors should file an ICLA.
=> Add ICLA Check

editor-settings.toml, src/config.ts, src/redux/videoSlice.ts
This patch allows the editor to load files from the local server if possible (indicated by Opencast). This means that, for example, with the default configuration, files are no longer loaded from the admin server when the editor is accessed on presentation, causing authentication problems.
=> Load locally if possible

src/globalKeys.ts, src/main/KeyboardControls.tsx
Currently, users can not play/pause the video in the subtitle input field. These changes solve this problem by introducing an alternate hotkey `Strg` + `Alt` + `Space` to play and pause videos.
Resolves #901
=> Additional Hotkey to play back video in the subtitle editor

package-lock.json, package.json, src/main/Metadata.tsx, src/redux/metadataSlice.ts
Updates the dependency 'reduxjs/toolkit' to version 1.9.3. Fixes associated type errors by explicitely stating the types for certain CaseReducers.
Replaces #994
=> Update reduxjs/toolkit to 1.9.3

src/i18n/locales/en-US.json, src/main/WorkflowSelection.tsx
This patch updates the error message users get if there are no workflows usable by the editor. It sounded a bit weird and I didn't quite agree with the grammar :D
=> No Workflow Error

src/main/MainContent.tsx, src/main/Save.tsx, src/redux/subtitleSlice.ts
Upon closing the editor window, a "Unsaved changes" dialog is displayed if you have unsaved changes. However, this was not the case for changes made to subtitles. Now it should be.
Resolves #1026.
=> Display "Unsaved changes" for subtitles

src/i18n/i18next.d.ts, src/index.tsx, src/main/CuttingActions.tsx, src/main/Discard.tsx, src/main/Error.tsx, src/main/FinishMenu.tsx, src/main/KeyboardControls.tsx, src/main/Landing.tsx, src/main/MainMenu.tsx, src/main/Metadata.tsx, src/main/Save.tsx, src/main/SubtitleSelect.tsx, src/main/SubtitleTimeline.tsx, src/main/TheEnd.tsx, src/main/Thumbnail.tsx, src/main/Timeline.tsx, src/main/Video.tsx, src/main/WorkflowConfiguration.tsx, src/main/WorkflowSelection.tsx
Adds type checking to our translation library.  This will help us avoid using translation strings that do not exist.
I've use "TFuncKey" as the type for cases where we pass a variable string  instead of a literal. This could arguably be improved upon in the future.
Also some related cleanup.
Closes #977
=> Add type checking to i18n

README.md
As I've recently been asked if there is any way to avoid waveform generation, it occured to me that we never documented #695. This seeks to remedy that by adding a short paragraph to the ReadMe.
=> Add infos on waveform to ReadMe

package-lock.json, package.json, src/main/SubtitleListEditor.tsx
Also fixes a non-typed object that blocked the update
=> Update react-virtualized-auto-resizer to 1.0.20

.eslintrc.js, package-lock.json, package.json
Else eslint will throw an error on that. Since updating to React 18 is non-trivial, we need to disable this rule for now.
=> Disable eslint "react/no-deprecated"

README.md, editor-settings.toml, public/editor-settings.toml, src/config.ts, src/i18n/locales/de-DE.json, src/i18n/locales/en-US.json, src/main/Finish.tsx, src/main/Save.tsx, src/main/TheEnd.tsx
After finishing the editing, the user can now navigate back to the calling system using a button. For this, the integrating system can pass a `callbackUrl` url parameter to provide a return link. In the editor settings, the prefixes of the allowed callback urls must be provided in the `allowedCallbackPrefixes` option to prevent malicious callback urls.
=> Add callback url for integration (#1084)

package-lock.json, package.json
Bumps the version of `@opencast/appkit` to 0.2.1,
which adds visible borders around the language and appearance dropdowns in high contrast mode.
Resolves #1156.
=> Bump appkit version for high contrast borders

src/cssStyles.tsx, src/main/CuttingActions.tsx, src/main/TrackSelection.tsx
Fixes #1186 
color property of the icon-class is overriding the color property of button-class on hover.
=> Fix #1186, incorrect color of btn icons on hover

src/main/Thumbnail.tsx
The "Generate All" and "Use for all tracks" buttons in the thumbnail view don't really serve a purpose when there is only one track. "Generate All" does the same thing as "Generate", and "Use for all tracks" does straight up nothing. Therefore, we might as well not display them if there is but a single track.
Fixes  #1206.
=> Don't show certain thumbnail buttons for single track

src/main/Thumbnail.tsx, src/main/VideoPlayers.tsx
Currently in the thumbnail view, the videos are the same size as the thumbnails. However, the outlines surrounding them are different, as the outline around the thumbnails also contains buttons. This enlarges the videos to make the outlines have the same width.
Partially addresses #1207. From a usability point-of-view, I don't think making the timeline the same width as the stuff above it is currently reasonable. Since we cannot zoom into the timeline (yet™), it should be as wide as possible.
=> Thumbnail make boxes same size

src/main/Body.tsx, src/main/Cutting.tsx, src/main/CuttingActions.tsx, src/main/Discard.tsx, src/main/Error.tsx, src/main/Finish.tsx, src/main/FinishMenu.tsx, src/main/Header.tsx, src/main/Lock.tsx, src/main/MainContent.tsx, src/main/MainMenu.tsx, src/main/Metadata.tsx, src/main/Save.tsx, src/main/Subtitle.tsx, src/main/SubtitleEditor.tsx, src/main/SubtitleListEditor.tsx, src/main/SubtitleSelect.tsx, src/main/SubtitleTimeline.tsx, src/main/SubtitleVideoArea.tsx, src/main/TheEnd.tsx, src/main/Thumbnail.tsx, src/main/Timeline.tsx, src/main/TrackSelection.tsx, src/main/VideoControls.tsx, src/main/VideoPlayers.tsx, src/main/WorkflowConfiguration.tsx, src/main/WorkflowSelection.tsx, src/redux/store.ts
`useAppDispatch` and `useAppSelector` are typed version of `useDispatch` and `useSelector`. This change is mostly to follow convention and make our code more consistent overall for the few cases were it actually helps or is required.
=> Declare project-wide useAppDispatch and useAppSelector

src/main/SubtitleEditor.tsx
Putting our selectors into ´createSlice` caused one of the selectors to be called incorrectly. This fixes that.
=> Fix subtitle select page crashing

src/main/SubtitleEditor.tsx, src/main/WorkflowConfiguration.tsx, src/redux/subtitleSlice.ts
Creating a new subtitle from scratch was broken, because the text in the cues was not saved to Opencast.
This fixes that.
Includes #1266. 
Should also fix #888.
=> Fix subtiles not saved for new subtitles 

src/i18n/locales/en-US.json, src/main/SubtitleSelect.tsx
Satisfies a material-ui quirk concerning `ThemedTooltip` and button. Will now correctly show a tooltip on the subtitle select button even if it is disabled.
=> Fix tooltip not showing on subtitle select button

src/img/opencast-editor.svg
Starting the editor will prompt an error message about spelling in our opencast-editor.svg. This complies with the solution suggested by the error message, also because I'm fairly certain that we do not care about this parameter at all.
=> Fix web console error message about xmlnsSvg

.eslintrc.js, .github/workflows/playwright-test.yml, config-overrides.js, index.html, package-lock.json, package.json, playwright.config.ts, src/config.ts, src/i18n/config.tsx, src/index.tsx, src/main/CuttingActions.tsx, src/main/Header.tsx, src/main/MainMenu.tsx, src/main/TrackSelection.tsx, tsconfig.json, vite.config.ts
One way to resolve #1253.
Demonstration of replacing create-react-app with vite. Got this working in a couple hours.
Vite was chosen because:
- Straightforward migration
- Relatively similar set of opinions as CRA
- Optimized for single page applications like ours
- Popular
Fairly happy with this so far, if only for the fact that it let's us get rid of some old tech debt. And vite is indeed miles faster in development than CRA. Also gets the size of our build folder down from 9,8M to 1,7M.
ToDos:
- Playwright broke, fix it.
=> Replace CRA with Vite

src/main/SubtitleSelect.tsx
The language tag contains a space between the colon and the language part. This commit removes the space so the tag looks like `lang:de` instead of `lang: de`.
=> Remove whitespace

.github/build-release.sh, index.html, src/config.ts, vite.config.ts
Vite ignores all environment variables which do not start with VITE_.
=> Replace REACT_ environment variables

.github/mock/editor/ID-dual-stream-demo/metadata.json, .gitignore, src/config.ts, src/i18n/config.tsx, src/i18n/locales.json, src/i18n/locales/locales.json, tests/metadata.test.ts, vite.config.ts
Vite does not honor the PUBLIC_URL environment variable; we need to set the base via that variable to support building versions with a path different from the root.
=> Set vite base

.eslintrc.js, src/config.ts, src/cssStyles.tsx, src/import-png.d.ts, src/main/Metadata.tsx, src/main/SubtitleSelect.tsx, src/main/Thumbnail.tsx, src/main/Timeline.tsx, src/main/VideoPlayers.tsx, src/redux/metadataSlice.ts, src/redux/subtitleSlice.ts, src/redux/videoSlice.ts
Adds more typing, but also adds a few eslint exceptions. I tried to keep the exceptions to types were it makes sense to keep `any` (i.e. third party libraries returning it or just cases were we don't care about the contents of a variable). This may be controversial though.
=> Enforce eslint no-explicit-any

src/i18n/locales/de-DE.json, src/i18n/locales/en-US.json, src/main/WorkflowSelection.tsx
Change the the wording of the "Start processing" button to "Save and publish changes" to better differentiate the buttons. Additionally, this should highlight that videos can be published with this button.
I haven't changed the existing translations, as I don't know what to do with them.
Related #1131
=> Change wordings in finish menu

src/redux/videoSlice.ts
The hard-coded threshold of 3s for skipping to the previous segment instead of skipping to the start of the segment can be too long for short videos, where visually, you are far away from the actual cut mark.
This patch fixes the problem by making this a dynamic threshold based on the video duration with a minimum of 0.5s (guarding against a non-set video duration) and a maximum of 3s.
=> Dynamic skip threshold

.github/release.yml
This patch fixes the label configuration for release notes. Most notably, other patches was never picked up since only `*` is a special value.
=> Fix releaste note configuration

editor-settings.toml
This patch replaces the todo mark for linking the subtitle tags documentation with the actual link to that documentation.
=> Link subtitle tag documentation

.github/workflows/create-release.yml, .github/workflows/playwright-test.yml, .github/workflows/update-test.yml, .github/workflows/update.yml
This patch updates the Node.js version used in several GitHub Action workflows to Node.js 20 which is the current LTS version.
=> Update to Node.js 20 (current LTS)

README.md
opencast/opencast#5769 will soon add a section to the upstream translation docs regarding how to edit keys so let's link that here as well.
=> Document and link translation rules

.github/workflows/update-test.yml
Instead of just specifying the main branch, this pull request specifies the latest major version of thollander/actions-comment-pull-request to use in GitHub Actions. We don't know how this action changes and tracking the default branch may cause this to break at any time. We can always update using Dependabot.
=> Specify version of comment action

src/main/VideoPlayers.tsx
This PR fixes #1382 
The problem is simply the lack of support in Safari that it could not recognize and allocate height based on aspect ratio.
The reason behind it, is because Safari support for aspect ratio was introduced in v15, and it is far behind the other browsers.
In order to tackle that, this PR just introduces a wrapper around the React video player, by allowing it to have the height of 100% set for each video! That means now the height is not more a burden on browser to calculate based on aspect ratio!
The wrapper on the other hand is responsible to occupy the width and height designed for this section and let the video just take up the space it needs!
NOTE: it not only works for dual video, but the single video is covered too!
- you would need to have Safari to see the …
=> Fix aspect ratio video box size in Safari

src/cssStyles.tsx, src/main/Discard.tsx, src/main/Error.tsx, src/main/FinishMenu.tsx, src/main/Header.tsx, src/main/KeyboardControls.tsx, src/main/MainContent.tsx, src/main/MainMenu.tsx, src/main/Save.tsx, src/main/SubtitleEditor.tsx, src/main/SubtitleListEditor.tsx, src/main/SubtitleSelect.tsx, src/main/SubtitleVideoArea.tsx, src/main/TheEnd.tsx, src/main/Thumbnail.tsx, src/main/TrackSelection.tsx, src/main/VideoControls.tsx, src/main/VideoPlayers.tsx, src/main/WorkflowConfiguration.tsx, src/main/WorkflowSelection.tsx, src/util/utilityFunctions.ts
According to our browserslist config, this is only needed for very old versions of mobile Safari, which we don't support anyway.
cf. https://browsersl.ist/#q=%3E0.2%25%0Anot+dead%0Anot+op_mini+all%0Anot+fully+supports+flexbox-gap
=> Remove flex gap polyfill

src/main/SubtitleTimeline.tsx
In the subtitle editor timeline, it was only possible to change the start time of a segment by drag and drop. This change makes it possible to change the end time in the same way.
Resolves #1314
=> Subtitle editor: Allow to change end time of segment in timeline by drag and drop

src/main/Header.tsx
Handles the static asset `opencast-editor.svg` according to the vite documentation.
https://vitejs.dev/guide/assets#the-public-directory
=> Fix opencast editor logo

src/main/VideoPlayers.tsx
If the editor has multiple videos, it will consider one of them the "primary" video, from which it will play back audio. Even if that "primary" video does not have any audio.
This changes the logic so that the first video with audio the editor comes across is made the "primary" video, so that there should always be audio playing if audio is available.
=> Fix editor not playing audio due to video order

.github/build-release.sh
`date --utc` is not POSIX and macOS doesn't have it. `-u` is the standard equivalent.
cf. opencast/opencast-admin-interface#326.
=> Fix the release script for macOS

.github/workflows/check-icla.yml
Copied from https://github.com/opencast/opencast/pull/6238
The tool we use for checking if contributors signed their ICLA is failing to install on CI runs with new Python versions since we just install it system-wide. While that may not be good practice on your local machine, this shouldn't matter in the CI since we immediately throw away the machine anyway.
=> Fix ICLA Check

.github/workflows/crowdin-download-translations.yml, .github/workflows/crowdin-upload-keys.yml
This patch fixes the crowdin integration. The previous Actions workflow would generate the necessary patches gut never stage commit them to the repository.
This also renames the workflows so they have names identical to what we use in the admin interface.
=> Fix Crowdin integration

src/main/TheEnd.tsx
This patch fixes the issue that the text and the check mark icon of the end screen is pushed to the top of the end space with basically no spacing. This is caused by an incorrect CSS calculation.
---
Before:
After:
=> Properly center and space end screen

src/main/MainMenu.tsx, src/main/Metadata.tsx, src/main/Save.tsx, src/main/WorkflowConfiguration.tsx, src/redux/metadataSlice.ts, src/redux/workflowPostAndProcessSlice.ts, src/redux/workflowPostSlice.ts, src/types.ts
Fixes #485.
When the user was saving (or saving and processing), we would sent two sequential POST requests, one for metadata and one for all the rest. This unifies the requests into a single one.
Requires backend changes: https://github.com/opencast/opencast/pull/6241
=> Unify save requests

src/react-app-env.d.ts
A file used by create-react-app. Since we switched to Vite, we don't need this anymore.
=> Remove CRA ts definition file

src/redux/videoSlice.ts
This patch makes the forward button jump to the end of the video if you are currently in the last segment.
The previous behavior, jumping to the **beginning** of the last segment, made it so that the forward button sometimes made you go backwards in the video. This is especially confusing if there is only one segment, in which case the forward button put you at the beginning of the video.
=> Make behavior of forward button more intuitive

src/main/Save.tsx
Fixes #1520.
We were not sending workflow ids anymore, so accordingly workflows were not started. This fixes that.
Make sure https://github.com/opencast/opencast/pull/6241/files is merged in the Opencast you test this with.
=> Fix workflows not starting

src/main/SubtitleEditor.tsx
Fixes https://github.com/opencast/opencast-editor/issues/1523.
Some button at the top of the subtitle editor were not the right height. This patch should fix that.
No special dependencies, can be tested as is. Install and look at the top row of buttons in the subtitle editor. You may need to configure `show = true` for subtitles in the `editor-settings.toml`.
=> Fix subtitle button height

src/main/SubtitleEditor.tsx, src/main/SubtitleSelect.tsx, src/main/TrackSelection.tsx, src/main/VideoPlayers.tsx, src/main/WorkflowSelection.tsx
Fixes various small issues that don't directly impact functionality, but that eslint and typescript complain about.
Can be tested as usual.
=> Fix various eslint and typescript complaints

src/redux/videoSlice.ts
This patch allows the editor to load the waveform images from the local server if possible (indicated by Opencast).
The mechanism is identical to what we already use for tracks.
This patch bases on #1010
=> Load waveform images locally if possible
